version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
references:
  yarn_cache_key: &yarn_cache_key yarn-v1-{{ checksum "yarn.lock" }}
jobs:
  build:
    docker:
      - image: circleci/node:10.13
        environment:
          PGUSER: postgres
          PG_USER: postgres
          PG_HOST: localhost
      - image: postgis/postgis:12-3.0-alpine
        environment:
          PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: warthog-test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Waiting for Postgres to be ready
          command: |
            # Wait for 10 seconds for Postgres to respond
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1
      - restore_cache:
          keys:
            - *yarn_cache_key
            - yarn-v1-
      - run:
          name: dependencies
          command: yarn install --frozen-lockfile    
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test
        - run:
          name: config
          command: WARTHOG_ENV=production yarn run config
        - run:
          name: deploy
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo "On master branch, pushing to Production"
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
            else
              echo "On branch $CIRCLE_BRANCH - skipping deploy"
            fi
        - run:
          name: migrate
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              echo "On master branch, running DB migrations"
              DEBUG=* WARTHOG_ENV=production yarn run config && yarn warthog db:migrate
            else
              echo "On branch $CIRCLE_BRANCH - skipping deploy"
            fi
        - save_cache:
          key: *yarn_cache_key
          paths: ~/circleci/node_modules
